apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dataprodukt-forstegangsbehandling
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
  readiness:
    path: isready
  resources:
    limits:
      memory: 500Mi
    requests:
      cpu: 200m
      memory: 500Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: {{pool}}
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        diskAutoresize: true
        tier: db-custom-1-3840
        databases:
          - name: forstegangsbehandling
            envVarPrefix: DATABASE
            users:
              - name: bigquery_datastream
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
  secureLogs:
    enabled: true
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: cg-dataprodukt-forstegangsbehandling-v1
    - name: KAFKA_RESET_POLICY
      value: "earliest"
