apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dataprodukt-forstegangssoknad
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
  readiness:
    path: isready
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 500Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: {{pool}}
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        diskAutoresize: true
        databases:
            envVarPrefix: DATABASE
  secureLogs:
    enabled: true
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: cg-dataprodukt-forstegangssoknad-v1