name: Deploy forstegangsbehandling

on:
  push:
    paths:
      - "forstegangsbehandling/**"
      - "felles/**"
      - "build.gradle.kts"
      - "settings.gradle.kts"
      - ".github/workflows/førstegangsbehandling.yml"
    branches:
      - main
permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.x'
          cache: 'gradle'
      - name: test and build
        run: ./gradlew :forstegangsbehandling:test :forstegangsbehandling:build --info
      - name: Build container image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: tbd
          docker_context: forstegangsbehandling
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deployDev:
    name: deploy to dev
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: forstegangsbehandling/deploy/nais.yml
          VARS: forstegangsbehandling/deploy/dev.yml
          VAR: image=${{ needs.build.outputs.image }}

  deployProd:
    name: deploy to prod
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: forstegangsbehandling/deploy/nais.yml
          VARS: forstegangsbehandling/deploy/prod.yml
          VAR: image=${{ needs.build.outputs.image }}
